name: 'Accion Super'
description: 'My new Action'
inputs:
  ssh_key:
     description: "Deployment SSH key"
     required: true
runs:
  using: "composite"
  steps:
      - name: Install dependencies
        run: |
          echo hello
        shell: bash
        env:
          SSH_KEY: ${{ inputs.ssh_key }}

