name: 'Accion Super'
description: 'My new Action'
inputs:
  ssh_key:
     description: "Deployment SSH key"
     required: true
runs:
  using: "composite"
  steps:
      - name: Install dependencies
        run: npm ci
        shell: bash

      - name: Compile and copy
        run: mkdir _deploy && ./node_modules/.bin/gulp copy
        shell: bash

      - name: SSH
        run: |
          cat ~/.ssh/known_hosts
          mkdir -p ~/.ssh
          echo $SSH_KEY > ~/.ssh/id_ed25519
          ssh git@git.wpengine.com info
        shell: bash
        env:
          SSH_KEY: ${{ inputs.ssh_key }}


