name: 'Accion Super'
description: 'My new Action'
inputs:
  ssh_key:
     description: "Deployment SSH key"
     required: true
runs:
  using: "composite"
  steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          touch ~/.ssh/id_ed25519
          touch ~/.ssh/known_hosts
          chmod 600 ~/.ssh/id_ed25519
          echo -e "$SSH_KEY" | tr -d '\r' > ~/.ssh/id_ed25519
          ssh-keyscan git.wpengine.com >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          ssh git@git.wpengine.com info
        shell: bash
        env:
          SSH_KEY: ${{ inputs.ssh_key }}

      - name: Install dependencies
        run: npm ci
        shell: bash

      - name: Checkout GitPush repository
        run: git clone git@git.wpengine.com:silentpushtr.git
        shell: bash

      - name: Compile and copy
        run: ./node_modules/.bin/gulp copy
        shell: bash

