name: 'Accion Super'
description: 'My new Action'
runs:
  using: "composite"
  steps:
      - name: Install dependencies
        run: |
          mkdir _deploy
          npm ci
          ./node_modules/.bin/gulp copy
          ls -R _deploy
        shell: bash

