name: 'Punch theme compile'
description: 'Compiles a Punch theme'
runs:
  using: "composite"
  steps:
      - name: Install Node dependencies
        run: npm ci
        shell: bash

      - name: Compile assets
        run: |
          ./node_modules/.bin/gulp copy
          ls -R
        shell: bash

