name: 'Accion Super'
description: 'My new Action'
runs:
  using: "composite"
  steps:
      - name: Install dependencies
        run: npm ci
        shell: bash

      - name: Compile and copy
        run: mkdir _deploy && ./node_modules/.bin/gulp copy
        shell: bash

      - name: Install dependencies
        run: |
          ssh git@git.wpengine.com info
        shell: bash

