name: 'Accion Super'
description: 'My new Action'
runs:
  using: "composite"
  steps:
      - name: Install dependencies
        run: |
          echo hello
        shell: bash
        env:
          SSH_KEY: ${{ secrets.key }}

